Repository team-go-higher/backend, pull requests merged in 2023-09, with the labels that each got.

#13 [DOCS] Swagger Set up
  in-adapter-api/build.gradle
  in-adapter-api/src/main/java/gohigher/config/SwaggerConfig.java
  in-adapter-api/src/main/resources/application.yml
Labels: 📖 documentation

#14 [FEATURE] kakao OAuth2 로그인 구현
  core-application/src/main/java/gohigher/port/in/OAuth2CommandPort.java
  core-application/src/main/java/gohigher/port/out/OAuth2PersistenceCommandPort.java
  core-application/src/main/java/gohigher/port/out/OAuth2PersistenceQueryPort.java
  core-application/src/main/java/gohigher/usecase/OAuth2CommandService.java
  core-application/src/main/java/gohigher/usecase/OauthLoginInUseCase.java
  core-domain/src/main/java/gohigher/user/User.java
  in-adapter-api/src/main/java/gohigher/config/SpringSecurityConfig.java
  in-adapter-api/src/main/java/gohigher/oauth2/AuthenticationSuccessHandler.java
  in-adapter-api/src/main/java/gohigher/oauth2/OAuth2Attribute.java
  in-adapter-api/src/main/java/gohigher/oauth2/OauthUserService.java
  in-adapter-api/src/main/java/gohigher/oauth2/user/GoogleOAuth2User.java
  in-adapter-api/src/main/java/gohigher/oauth2/user/KakaoOAuth2User.java
  in-adapter-api/src/main/java/gohigher/oauth2/user/OAuth2UserInfo.java
  in-adapter-api/src/main/java/gohigher/oauth2/user/OAuth2UserInfoFactory.java
  out-adapter-persistence-jpa/src/main/java/gohigher/user/OAuth2Repository.java
  out-adapter-persistence-jpa/src/main/java/gohigher/user/UserJpaEntity.java
  out-adapter-persistence-jpa/src/main/java/gohigher/user/UserRepository.java
Labels: ⚡️ feature

#19 [REFACTOR] Spring Security 모듈 분리
  .github/pull_request_template.md
  in-adapter-api/build.gradle
  security/build.gradle
  security/src/main/java/gohigher/config/SpringSecurityConfig.java
  security/src/main/java/gohigher/oauth2/AuthenticationSuccessHandler.java
  security/src/main/java/gohigher/oauth2/OauthUserService.java
  security/src/main/java/gohigher/oauth2/user/GoogleOAuth2User.java
  security/src/main/java/gohigher/oauth2/user/KakaoOAuth2User.java
  security/src/main/java/gohigher/oauth2/user/OAuth2UserInfo.java
  security/src/main/java/gohigher/oauth2/user/OAuth2UserInfoFactory.java
  settings.gradle
Labels: 🛠️ refactor

#20 [FEATURE] 공통 개발환경 확립
  bootstrap/build.gradle
  bootstrap/src/main/java/gohigher/GohigherApplication.java
  bootstrap/src/main/resources/application-local.yml
  core-domain/src/main/java/gohigher/application/ApplicationErrorCode.java
  core-domain/src/main/java/gohigher/global/exception/ErrorCode.java
  core-domain/src/main/java/gohigher/global/exception/GlobalErrorCode.java
  core-domain/src/main/java/gohigher/global/exception/GoHigherException.java
  in-adapter-api/build.gradle
  in-adapter-api/src/main/java/gohigher/controller/response/ApiResponse.java
  in-adapter-api/src/main/java/gohigher/controller/response/ErrorResponse.java
  in-adapter-api/src/main/java/gohigher/exception/ControllerAdvice.java
  in-adapter-api/src/main/resources/application-docs.yml
  out-adapter-persistence-jpa/src/main/resources/application-persistence-local.yml
  settings.gradle
Labels: ⚡️ feature

#25 [FEATURE] 토큰 발급 기능 및 토큰을 통한 인증 기능 구현
  bootstrap/src/main/resources/application-local.yml
  core-application/src/main/java/gohigher/port/in/OAuth2CommandPort.java
  core-application/src/main/java/gohigher/port/in/UserCommandPort.java
  core-application/src/main/java/gohigher/port/in/UserQueryPort.java
  core-application/src/main/java/gohigher/port/out/OAuth2PersistenceCommandPort.java
  core-application/src/main/java/gohigher/port/out/OAuth2PersistenceQueryPort.java
  core-application/src/main/java/gohigher/port/out/UserPersistenceCommandPort.java
  core-application/src/main/java/gohigher/port/out/UserPersistenceQueryPort.java
  core-application/src/main/java/gohigher/usecase/OAuth2CommandService.java
  core-application/src/main/java/gohigher/usecase/UserCommandService.java
  core-application/src/main/java/gohigher/usecase/UserQueryService.java
  core-domain/src/main/java/gohigher/user/User.java
  core-domain/src/main/java/gohigher/user/UserErrorCode.java
  core-domain/src/main/java/gohigher/user/auth/AuthErrorCode.java
  core-domain/src/main/java/gohigher/user/auth/Provider.java
  in-adapter-api/build.gradle
  out-adapter-persistence-jpa/src/main/java/gohigher/user/OAuth2Repository.java
  out-adapter-persistence-jpa/src/main/java/gohigher/user/UserJpaEntity.java
  out-adapter-persistence-jpa/src/main/java/gohigher/user/UserPersistenceCommandAdapter.java
  out-adapter-persistence-jpa/src/main/java/gohigher/user/UserPersistenceQueryAdapter.java
  out-adapter-persistence-jpa/src/main/java/gohigher/user/UserRepository.java
  security/build.gradle
  security/src/main/java/gohigher/config/SpringSecurityConfig.java
  security/src/main/java/gohigher/jwt/JwtAuthFilter.java
  security/src/main/java/gohigher/jwt/JwtExceptionFilter.java
  security/src/main/java/gohigher/jwt/support/AuthorizationExtractor.java
  security/src/main/java/gohigher/jwt/support/CookieProvider.java
  security/src/main/java/gohigher/jwt/support/JwtProvider.java
  security/src/main/java/gohigher/jwt/support/RoleGrantedAuthority.java
  security/src/main/java/gohigher/oauth2/AuthenticationSuccessHandler.java
  security/src/main/java/gohigher/oauth2/OauthUserService.java
  security/src/main/java/gohigher/oauth2/handler/AuthenticationFailureHandler.java
  security/src/main/java/gohigher/oauth2/handler/AuthenticationSuccessHandler.java
  security/src/main/java/gohigher/oauth2/user/GoogleOAuth2User.java
  security/src/main/java/gohigher/oauth2/user/KakaoOAuth2User.java
  security/src/main/java/gohigher/oauth2/user/OAuth2UserInfo.java
  security/src/main/java/gohigher/oauth2/user/OAuth2UserInfoFactory.java
  security/src/main/java/gohigher/response/ErrorResponse.java
  security/src/main/java/gohigher/response/GoHigherResponse.java
  security/src/main/resources/application-auth.yml
  security/src/main/resources/application-jwt.yml
  security/src/test/java/gohigher/.gitkeep
  security/src/test/java/gohigher/support/CookieProviderTest.java
  security/src/test/java/gohigher/support/JwtProviderTest.java
Labels: ⚡️ feature

#34 [FEATURE] 간편 지원서 등록 기능 구현
  core-application/build.gradle
  core-application/src/main/java/gohigher/application/port/in/ApplicationCommandPort.java
  core-application/src/main/java/gohigher/application/port/in/SimpleApplicationRequest.java
  core-application/src/main/java/gohigher/application/port/in/SimpleProcessRequest.java
  core-application/src/main/java/gohigher/application/port/out/persistence/ApplicationPersistenceCommandPort.java
  core-application/src/main/java/gohigher/application/service/ApplicationCommandService.java
  core-domain/src/main/java/gohigher/application/Application.java
  core-domain/src/main/java/gohigher/common/JobInfo.java
  core-domain/src/main/java/gohigher/common/JobInfoErrorCode.java
  core-domain/src/main/java/gohigher/common/ProcessType.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationCommandController.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationCommandControllerDocs.java
  in-adapter-api/src/main/java/gohigher/auth/support/Login.java
  in-adapter-api/src/main/java/gohigher/exception/ControllerAdvice.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationPersistenceCommandAdapter.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationJpaEntity.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationProcessJpaEntity.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationProcessRepository.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationRepository.java
  out-adapter-persistence-jpa/src/main/java/gohigher/recruitment/entity/RecruitmentJpaEntity.java
  out-adapter-persistence-jpa/src/main/java/gohigher/recruitment/entity/RecruitmentProcessJpaEntity.java
  out-adapter-persistence-jpa/src/main/java/gohigher/recruitment/entity/RecruitmentRepository.java
Labels: ⚡️ feature

#36 [BUILD] 멀티모듈 build 설정
  build.gradle
  core-application/build.gradle
  core-domain/build.gradle
  in-adapter-api/build.gradle
  out-adapter-persistence-jpa/build.gradle
  security/build.gradle
Labels: 🚀 build

#51 [REFACTOR] OAuth 인증 키 값 변경
  security/src/main/resources/application-auth.yml
Labels: 🛠️ refactor

#55 [REFACTOR] 로그인 요청에 대한 응답 변경
  in-adapter-api/src/main/java/gohigher/auth/TokenController.java
  in-adapter-api/src/main/java/gohigher/auth/TokenControllerDocs.java
  security/src/main/java/gohigher/oauth2/handler/AuthenticationSuccessHandler.java
  security/src/main/resources/application-auth.yml
Labels: 🚨 fix, 🛠️ refactor

#47 [TEST] Spring Security Test
  bootstrap/src/main/java/gohigher/encryption/config/YamlEncryptionConfig.java
  bootstrap/src/test/java/gohigher/security/SpringSecurityTest.java
  core-application/build.gradle
  core-application/src/test/java/gohigher/usecase/OAuth2CommandServiceTest.java
  core-domain/build.gradle
  core-domain/src/main/java/gohigher/common/JobInfo.java
  core-domain/src/main/java/gohigher/user/auth/AuthErrorCode.java
  core-domain/src/main/java/gohigher/user/auth/Provider.java
  core-domain/src/test/java/gohigher/user/ProviderTest.java
  out-adapter-persistence-jpa/build.gradle
  out-adapter-persistence-jpa/src/test/java/gohigher/GoHigherApplicationTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/user/UserPersistenceCommandAdapterTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/user/UserPersistenceQueryAdapterTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/user/UserRepositoryTest.java
  out-adapter-persistence-jpa/src/test/resources/application.yml
  security/src/main/java/gohigher/oauth2/user/KakaoOAuth2User.java
  security/src/test/java/gohigher/oauth2/user/GoogleOAuth2UserTest.java
  security/src/test/java/gohigher/oauth2/user/KakaoOAuth2UserTest.java
  security/src/test/java/gohigher/oauth2/user/OAuth2UserInfoFactoryTest.java
Labels: 🧪 test

#56 [FEATURE] 지원서 상세 등록 기능 구현
  core-application/src/main/java/gohigher/application/port/in/ApplicationCommandPort.java
  core-application/src/main/java/gohigher/application/port/in/SimpleApplicationProcessRequest.java
  core-application/src/main/java/gohigher/application/port/in/SimpleApplicationRequest.java
  core-application/src/main/java/gohigher/application/port/in/SpecificApplicationProcessRequest.java
  core-application/src/main/java/gohigher/application/port/in/SpecificApplicationRequest.java
  core-application/src/main/java/gohigher/application/service/ApplicationCommandService.java
  core-domain/src/main/java/gohigher/application/Application.java
  core-domain/src/main/java/gohigher/common/EmploymentType.java
  core-domain/src/main/java/gohigher/common/JobInfo.java
  core-domain/src/main/java/gohigher/common/JobInfoErrorCode.java
  core-domain/src/main/java/gohigher/recruitment/Recruitment.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationCommandController.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationCommandControllerDocs.java
  out-adapter-persistence-jpa/build.gradle
  out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationPersistenceCommandAdapter.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationJpaEntity.java
  out-adapter-persistence-jpa/src/main/java/gohigher/recruitment/entity/RecruitmentJpaEntity.java
  out-adapter-persistence-jpa/src/test/java/gohigher/GoHigherPersistenceTestContextLoader.java
Labels: ⚡️ feature

#62 [FIX] test 관련 코드 및 gradle 의존성 수정
  core-application/src/test/java/gohigher/usecase/UserCommandServiceTest.java
  core-domain/build.gradle
  out-adapter-persistence-jpa/src/test/java/gohigher/user/UserPersistenceCommandAdapterTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/user/UserPersistenceQueryAdapterTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/user/UserRepositoryTest.java
Labels: 🚨 fix

#52 [FEATURE] 캘린더 월별 지원서 목록 조회 API 생성
  build.gradle
  core-application/build.gradle
  core-application/src/main/java/gohigher/application/port/in/ApplicationQueryPort.java
  core-application/src/main/java/gohigher/application/port/in/CalenderApplicationRequest.java
  core-application/src/main/java/gohigher/application/port/in/CalenderApplicationResponse.java
  core-application/src/main/java/gohigher/application/port/in/SimpleApplicationProcessRequest.java
  core-application/src/main/java/gohigher/application/port/in/SpecificApplicationProcessRequest.java
  core-application/src/main/java/gohigher/application/port/in/SpecificApplicationRequest.java
  core-application/src/main/java/gohigher/application/port/out/persistence/ApplicationPersistenceQueryPort.java
  core-application/src/main/java/gohigher/application/service/ApplicationQueryService.java
  core-application/src/test/java/gohigher/application/port/in/CalenderApplicationRequestTest.java
  core-application/src/test/java/gohigher/application/service/ApplicationQueryServiceTest.java
  core-domain/build.gradle
  core-domain/src/main/java/gohigher/application/Application.java
  core-domain/src/main/java/gohigher/application/ApplicationErrorCode.java
  core-domain/src/main/java/gohigher/common/JobInfo.java
  core-domain/src/main/java/gohigher/common/Process.java
  core-domain/src/main/java/gohigher/recruitment/Recruitment.java
  core-domain/src/testFixtures/java/gohigher/application/ApplicationFixture.java
  core-domain/src/testFixtures/java/gohigher/application/ProcessFixture.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationQueryController.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationQueryControllerDocs.java
  out-adapter-persistence-jpa/build.gradle
  out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationPersistenceQueryAdapter.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationJpaEntity.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationProcessJpaEntity.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationRepository.java
  out-adapter-persistence-jpa/src/test/java/gohigher/GoHigherPersistenceTestContextLoader.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationPersistenceQueryAdapterTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/entity/ApplicationRepositoryTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/fixtureConverter/ApplicationFixtureConverter.java
Labels: ⚡️ feature

#58 [FEATURE] dev 환경을 위한 yml 설정
  bootstrap/src/main/resources/application-dev.yml
  bootstrap/src/main/resources/application-local.yml
  bootstrap/src/main/resources/application.yml
  in-adapter-api/src/main/resources/jwt/application-dev.yml
  in-adapter-api/src/main/resources/jwt/application-local.yml
  in-adapter-api/src/main/resources/jwt/application.yml
  out-adapter-persistence-jpa/src/main/resources/persistence/application-dev.yml
  out-adapter-persistence-jpa/src/main/resources/persistence/application-local.yml
  out-adapter-persistence-jpa/src/main/resources/persistence/application.yml
  security/src/main/resources/auth/application-dev.yml
  security/src/main/resources/auth/application-local.yml
  security/src/main/resources/auth/application.yml
Labels: ⚡️ feature, 🛠️ refactor

#59 [FEATURE] 지원서의 현재 진행 중인 전형 변경 API 구현
  core-application/build.gradle
  core-application/src/main/java/gohigher/application/port/in/ApplicationCommandPort.java
  core-application/src/main/java/gohigher/application/port/in/CurrentProcessUpdateRequest.java
  core-application/src/main/java/gohigher/application/port/in/SimpleApplicationRequest.java
  core-application/src/main/java/gohigher/application/port/in/SpecificApplicationProcessRequest.java
  core-application/src/main/java/gohigher/application/port/in/SpecificApplicationRequest.java
  core-application/src/main/java/gohigher/application/port/out/persistence/ApplicationPersistenceCommandPort.java
  core-application/src/main/java/gohigher/application/port/out/persistence/ApplicationPersistenceQueryPort.java
  core-application/src/main/java/gohigher/application/port/out/persistence/ApplicationProcessPersistenceQueryPort.java
  core-application/src/main/java/gohigher/application/service/ApplicationCommandService.java
  core-application/src/test/java/gohigher/application/service/ApplicationCommandServiceTest.java
  core-domain/build.gradle
  core-domain/src/main/java/gohigher/application/Application.java
  core-domain/src/main/java/gohigher/application/ApplicationErrorCode.java
  core-domain/src/main/java/gohigher/common/JobInfo.java
  core-domain/src/main/java/gohigher/common/JobInfoErrorCode.java
  core-domain/src/main/java/gohigher/common/Process.java
  core-domain/src/testFixtures/java/gohigher/application/ApplicationFixture.java
  core-domain/src/testFixtures/java/gohigher/application/ProcessFixture.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationCommandController.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationCommandControllerDocs.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationPersistenceCommandAdapter.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationPersistenceQueryAdapter.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationProcessPersistenceQueryAdapter.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationJpaEntity.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationProcessJpaEntity.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationProcessRepository.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationRepository.java
  out-adapter-persistence-jpa/src/test/java/gohigher/PersistenceAdapterTestContextLoader.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationPersistenceCommandAdapterTest.java
  out-adapter-persistence-jpa/src/test/resources/application.yml
Labels: ⚡️ feature

#66 [FEATURE] CORS 설정
  bootstrap/src/main/resources/application.yml
  in-adapter-api/src/main/java/gohigher/config/AuthConfig.java
  in-adapter-api/src/main/resources/cors/application.yml
  security/src/main/java/gohigher/config/SpringSecurityConfig.java
  security/src/main/resources/auth/application-dev.yml
Labels: ⚡️ feature

#72 [REFACTOR] Application의 userId 필드 삭제
  core-application/src/main/java/gohigher/application/port/in/CurrentProcessUpdateRequest.java
  core-application/src/main/java/gohigher/application/port/in/SimpleApplicationRequest.java
  core-application/src/main/java/gohigher/application/port/in/SpecificApplicationRequest.java
  core-application/src/main/java/gohigher/application/port/out/persistence/ApplicationPersistenceCommandPort.java
  core-application/src/main/java/gohigher/application/port/out/persistence/ApplicationPersistenceQueryPort.java
  core-application/src/main/java/gohigher/application/port/out/persistence/ApplicationProcessPersistenceQueryPort.java
  core-application/src/main/java/gohigher/application/service/ApplicationCommandService.java
  core-application/src/test/java/gohigher/application/service/ApplicationCommandServiceTest.java
  core-domain/src/main/java/gohigher/application/Application.java
  core-domain/src/main/java/gohigher/application/ApplicationErrorCode.java
  core-domain/src/testFixtures/java/gohigher/application/ApplicationFixture.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationCommandControllerDocs.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationPersistenceCommandAdapter.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationPersistenceQueryAdapter.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationProcessPersistenceQueryAdapter.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationJpaEntity.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationRepository.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationPersistenceCommandAdapterTest.java
Labels: 🛠️ refactor

#74 [FEATURE] 캘린더 일별 조회 API 구현
  core-application/src/main/java/gohigher/application/port/in/ApplicationQueryPort.java
  core-application/src/main/java/gohigher/application/port/in/CalendarApplicationRequest.java
  core-application/src/main/java/gohigher/application/port/in/CalendarApplicationResponse.java
  core-application/src/main/java/gohigher/application/port/in/CalenderApplicationResponse.java
  core-application/src/main/java/gohigher/application/port/in/DateApplicationRequest.java
  core-application/src/main/java/gohigher/application/port/in/DateApplicationResponse.java
  core-application/src/main/java/gohigher/application/port/in/DatePattern.java
  core-application/src/main/java/gohigher/application/port/in/ProcessResponse.java
  core-application/src/main/java/gohigher/application/port/out/persistence/ApplicationPersistenceQueryPort.java
  core-application/src/main/java/gohigher/application/port/out/persistence/ApplicationProcessPersistenceQueryPort.java
  core-application/src/main/java/gohigher/application/service/ApplicationQueryService.java
  core-application/src/main/java/gohigher/user/service/UserCommandService.java
  core-application/src/main/java/gohigher/user/service/UserQueryService.java
  core-application/src/test/java/gohigher/application/port/in/CalendarApplicationRequestTest.java
  core-application/src/test/java/gohigher/application/port/in/DateApplicationRequestTest.java
  core-application/src/test/java/gohigher/application/service/ApplicationCommandServiceTest.java
  core-application/src/test/java/gohigher/application/service/ApplicationQueryServiceTest.java
  core-application/src/test/java/gohigher/user/service/UserCommandServiceTest.java
  core-domain/src/main/java/gohigher/application/ApplicationErrorCode.java
  core-domain/src/main/java/gohigher/global/exception/GlobalErrorCode.java
  core-domain/src/testFixtures/java/gohigher/application/ApplicationFixture.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationCommandControllerDocs.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationQueryController.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationQueryControllerDocs.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationPersistenceQueryAdapter.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationJpaEntity.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationRepository.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationPersistenceCommandAdapterTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationPersistenceQueryAdapterTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/entity/ApplicationRepositoryTest.java
  out-adapter-persistence-jpa/src/test/resources/application.yml
  security/src/main/java/gohigher/oauth2/OauthUserService.java
Labels: ⚡️ feature

#77 [REFACTOR] application 테이블에 deadline 컬럼 삭제
  core-application/src/main/java/gohigher/application/port/in/SpecificApplicationRequest.java
  core-domain/src/main/java/gohigher/application/Application.java
  core-domain/src/main/java/gohigher/common/JobInfo.java
  core-domain/src/main/java/gohigher/recruitment/Recruitment.java
  core-domain/src/testFixtures/java/gohigher/application/ApplicationFixture.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationJpaEntity.java
  out-adapter-persistence-jpa/src/test/java/gohigher/fixtureConverter/ApplicationFixtureConverter.java
Labels: 🛠️ refactor

#82 [FEATURE] 지원서의 전형 타입에 따른 전형들을 응답하는 API 구현
  core-application/src/main/java/gohigher/application/port/in/ApplicationProcessByProcessTypeRequest.java
  core-application/src/main/java/gohigher/application/port/in/ApplicationProcessByProcessTypeResponse.java
  core-application/src/main/java/gohigher/application/port/in/ApplicationProcessQueryPort.java
  core-application/src/main/java/gohigher/application/port/in/ApplicationProcessQueryService.java
  core-application/src/main/java/gohigher/application/port/out/persistence/ApplicationProcessPersistenceQueryPort.java
  core-application/src/test/java/gohigher/application/port/in/ApplicationProcessQueryServiceTest.java
  core-domain/src/main/java/gohigher/application/ApplicationErrorCode.java
  core-domain/src/main/java/gohigher/common/Process.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationProcessQueryController.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationProcessQueryControllerDocs.java
  in-adapter-api/src/main/java/gohigher/config/WebConfig.java
  in-adapter-api/src/main/java/gohigher/support/enumconvertor/ProcessTypeConvertor.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationProcessPersistenceQueryAdapter.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationProcessRepository.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationPersistenceCommandAdapterTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationProcessPersistenceQueryAdapterTest.java
Labels: ⚡️ feature

#85 [FEATURE] 프론트 테스트용 yml 설정
  bootstrap/src/main/resources/application-test.yml
  security/src/main/resources/auth/application-test.yml
  security/src/main/resources/auth/application.yml
Labels: ⚡️ feature

#81 [FEATURE] 지원서 단일 조회 API 생성
  core-application/src/main/java/gohigher/application/port/in/ApplicationQueryPort.java
  core-application/src/main/java/gohigher/application/port/in/ApplicationResponse.java
  core-application/src/main/java/gohigher/application/port/out/persistence/ApplicationPersistenceQueryPort.java
  core-application/src/main/java/gohigher/application/service/ApplicationQueryService.java
  core-application/src/test/java/gohigher/application/service/ApplicationQueryServiceTest.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationQueryController.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationQueryControllerDocs.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationPersistenceQueryAdapter.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationJpaEntity.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationRepository.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationPersistenceQueryAdapterTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/entity/ApplicationRepositoryTest.java
Labels: ⚡️ feature

#87 [REFACTOR & FIX] https 보안 설정으로 인한 yml 업데이트 및 에러 픽스
  bootstrap/src/main/resources/application-dev.yml
  bootstrap/src/main/resources/application-local.yml
  bootstrap/src/main/resources/application-test.yml
  bootstrap/src/main/resources/application.yml
  in-adapter-api/src/main/java/gohigher/config/AuthConfig.java
  in-adapter-api/src/main/resources/cors/application-dev.yml
  in-adapter-api/src/main/resources/cors/application-local.yml
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationJpaEntity.java
  security/src/main/resources/auth/application-dev.yml
  security/src/main/resources/auth/application-test.yml
Labels: 🚨 fix, 🛠️ refactor

#88 [REFACTOR] redirect_url 값 수정
  security/src/main/resources/auth/application-dev.yml
  security/src/main/resources/auth/application-test.yml
Labels: 🚨 fix

#90 [FEATURE] 직무 목록 전체 조회 API 구현
  core-application/src/main/java/gohigher/application/port/in/ApplicationResponse.java
  core-application/src/main/java/gohigher/application/port/in/SimpleApplicationRequest.java
  core-application/src/main/java/gohigher/application/port/in/SpecificApplicationRequest.java
  core-application/src/main/java/gohigher/position/port/in/PositionQueryPort.java
  core-application/src/main/java/gohigher/position/port/in/PositionResponse.java
  core-application/src/main/java/gohigher/position/port/out/PositionPersistenceQueryPort.java
  core-application/src/main/java/gohigher/position/service/PositionQueryService.java
  core-domain/src/main/java/gohigher/application/Application.java
  core-domain/src/main/java/gohigher/common/JobInfo.java
  core-domain/src/main/java/gohigher/common/JobInfoErrorCode.java
  core-domain/src/main/java/gohigher/position/Position.java
  core-domain/src/main/java/gohigher/recruitment/Recruitment.java
  core-domain/src/testFixtures/java/gohigher/application/ApplicationFixture.java
  in-adapter-api/src/main/java/gohigher/position/PositionQueryController.java
  in-adapter-api/src/main/java/gohigher/position/PositionQueryControllerDocs.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationJpaEntity.java
  out-adapter-persistence-jpa/src/main/java/gohigher/position/entity/PositionJpaEntity.java
  out-adapter-persistence-jpa/src/main/java/gohigher/position/entity/PositionPersistenceQueryAdapter.java
  out-adapter-persistence-jpa/src/main/java/gohigher/position/entity/PositionRepository.java
  out-adapter-persistence-jpa/src/main/java/gohigher/recruitment/entity/RecruitmentJpaEntity.java
  out-adapter-persistence-jpa/src/test/java/gohigher/fixtureConverter/ApplicationFixtureConverter.java
Labels: ⚡️ feature

#75 [FEATURE] 칸반 지원서 목록 조회 API 생성
  core-application/src/main/java/gohigher/application/port/in/ApplicationQueryPort.java
  core-application/src/main/java/gohigher/application/port/in/KanbanApplicationDetailResponse.java
  core-application/src/main/java/gohigher/application/port/in/KanbanApplicationResponse.java
  core-application/src/main/java/gohigher/application/port/out/persistence/ApplicationPersistenceQueryPort.java
  core-application/src/main/java/gohigher/application/service/ApplicationQueryService.java
  core-application/src/test/java/gohigher/application/service/ApplicationQueryServiceTest.java
  core-domain/src/main/java/gohigher/application/Application.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationProcessQueryControllerDocs.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationQueryController.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationQueryControllerDocs.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationPersistenceCommandAdapter.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationPersistenceQueryAdapter.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationJpaEntity.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationRepository.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationPersistenceCommandAdapterTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationPersistenceQueryAdapterTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/entity/ApplicationRepositoryTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/fixtureConverter/ApplicationFixtureConverter.java
Labels: ⚡️ feature

#102 [FIX] 충돌 해결 과정에 남아있는 이전 코드 제거
  core-application/src/main/java/gohigher/application/port/in/KanbanApplicationDetailResponse.java
  core-domain/src/main/java/gohigher/application/Application.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationPersistenceQueryAdapter.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationJpaEntity.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationPersistenceQueryAdapterTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/entity/ApplicationRepositoryTest.java
Labels: 🚨 fix

#105 [FIX] security에서 preflight 요청 허용
  security/src/main/java/gohigher/config/SpringSecurityConfig.java
Labels: 🚨 fix

#97 [FEATURE] 날짜의 요청/응답 값을 "yyyy-MM-dd'T'HH:mm"으로 통일
  core-application/src/main/java/gohigher/application/port/in/SimpleApplicationProcessRequest.java
  core-domain/src/main/java/gohigher/global/exception/GlobalErrorCode.java
  in-adapter-api/src/main/java/gohigher/config/JacksonConfig.java
  in-adapter-api/src/main/java/gohigher/exception/ControllerAdvice.java
Labels: ⚡️ feature

#108 [REFACTOR] test용 db 설정
  bootstrap/src/main/resources/application-test.yml
  out-adapter-persistence-jpa/src/main/resources/persistence/application-test.yml
Labels: 🛠️ refactor

#113 [FEATURE] Request Validation 추가
  core-application/src/main/java/gohigher/application/port/in/SimpleApplicationProcessRequest.java
  core-application/src/main/java/gohigher/application/port/in/SimpleApplicationRequest.java
  core-application/src/main/java/gohigher/application/port/in/SpecificApplicationRequest.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationCommandControllerDocs.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationProcessQueryController.java
  in-adapter-api/src/main/java/gohigher/exception/ControllerAdvice.java
Labels: ⚡️ feature, 🛠️ refactor

#110 [REFACTOR] Jackson 예외 처리 객체 변경
  core-domain/src/main/java/gohigher/global/exception/GlobalErrorCode.java
  in-adapter-api/src/main/java/gohigher/exception/ControllerAdvice.java
Labels: 🛠️ refactor

#95 [FEATURE] 전형일이 작성되어 있지 않은 지원서 목록 조회 API 생성
  core-application/src/main/java/gohigher/application/port/in/ApplicationQueryPort.java
  core-application/src/main/java/gohigher/application/port/in/ApplicationResponse.java
  core-application/src/main/java/gohigher/application/port/in/PagingRequest.java
  core-application/src/main/java/gohigher/application/port/in/PagingResponse.java
  core-application/src/main/java/gohigher/application/port/in/UnscheduledApplicationResponse.java
  core-application/src/main/java/gohigher/application/port/out/persistence/ApplicationPersistenceQueryPort.java
  core-application/src/main/java/gohigher/application/service/ApplicationQueryService.java
  core-application/src/test/java/gohigher/application/service/ApplicationQueryServiceTest.java
  core-domain/src/main/java/gohigher/pagination/PaginationErrorCode.java
  core-domain/src/main/java/gohigher/pagination/PagingContainer.java
  core-domain/src/testFixtures/java/gohigher/application/ApplicationFixture.java
  core-domain/src/testFixtures/java/gohigher/application/ProcessFixture.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationQueryController.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationQueryControllerDocs.java
  out-adapter-persistence-jpa/build.gradle
  out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationPersistenceQueryAdapter.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationRepository.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationPersistenceQueryAdapterTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/entity/ApplicationRepositoryTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/fixtureConverter/ApplicationFixtureConverter.java
Labels: ⚡️ feature
