Repository team-go-higher/backend, pull requests merged in 2023-10, with the labels that each got.

#119 [REFACTOR] 페이징 응답 필드명 변경
  core-application/src/main/java/gohigher/application/port/in/PagingResponse.java
  core-application/src/main/java/gohigher/application/service/ApplicationQueryService.java
  core-domain/src/main/java/gohigher/pagination/PagingContainer.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationQueryControllerDocs.java
  in-adapter-api/src/main/java/gohigher/config/SwaggerConfig.java
Labels: 🛠️ refactor

#121 [REFACTOR] 전형일 없는 일정 조회 시 현재 전형만 불러오도록 변경
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationRepository.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/entity/ApplicationRepositoryTest.java
Labels: 🛠️ refactor

#103 [REFACTOR] Process Order를 Core에서 관리하도록 수정
  core-application/src/main/java/gohigher/application/port/in/SpecificApplicationRequest.java
  core-application/src/test/java/gohigher/application/service/ApplicationQueryServiceTest.java
  core-domain/src/main/java/gohigher/application/Application.java
  core-domain/src/main/java/gohigher/common/JobInfo.java
  core-domain/src/main/java/gohigher/common/Process.java
  core-domain/src/main/java/gohigher/common/Processes.java
  core-domain/src/main/java/gohigher/recruitment/Recruitment.java
  core-domain/src/test/java/gohigher/common/ProcessesTest.java
  core-domain/src/testFixtures/java/gohigher/application/ApplicationFixture.java
  core-domain/src/testFixtures/java/gohigher/application/ProcessFixture.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationPersistenceCommandAdapter.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationJpaEntity.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationProcessJpaEntity.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationPersistenceCommandAdapterTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationPersistenceQueryAdapterTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationProcessPersistenceQueryAdapterTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/entity/ApplicationRepositoryTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/fixtureConverter/ApplicationFixtureConverter.java
Labels: 🛠️ refactor

#123 [REFACTOR] 지원서 간편 등록 API 수정
  core-application/src/main/java/gohigher/application/port/in/ApplicationCommandPort.java
  core-application/src/main/java/gohigher/application/port/in/SimpleApplicationProcessRequest.java
  core-application/src/main/java/gohigher/application/port/in/SimpleApplicationRegisterResponse.java
  core-application/src/main/java/gohigher/application/port/out/persistence/ApplicationPersistenceCommandPort.java
  core-application/src/main/java/gohigher/application/service/ApplicationCommandService.java
  core-application/src/main/java/gohigher/application/service/ApplicationProcessQueryService.java
  core-application/src/test/java/gohigher/application/service/ApplicationProcessQueryServiceTest.java
  core-domain/src/main/java/gohigher/application/Application.java
  core-domain/src/main/java/gohigher/common/Process.java
  core-domain/src/main/java/gohigher/common/Processes.java
  core-domain/src/test/java/gohigher/common/ProcessesTest.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationCommandController.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationCommandControllerDocs.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationPersistenceCommandAdapter.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationJpaEntity.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationPersistenceCommandAdapterTest.java
Labels: 🛠️ refactor

#127 [FEATURE] 칸반 전형별 목록 조회 API 생성
  core-application/src/main/java/gohigher/application/port/in/ApplicationQueryPort.java
  core-application/src/main/java/gohigher/application/port/in/KanbanByProcessApplicationResponse.java
  core-application/src/main/java/gohigher/application/port/out/persistence/ApplicationPersistenceQueryPort.java
  core-application/src/main/java/gohigher/application/service/ApplicationQueryService.java
  core-application/src/test/java/gohigher/application/service/ApplicationQueryServiceTest.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationQueryController.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationQueryControllerDocs.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationPersistenceQueryAdapter.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationRepository.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationPersistenceQueryAdapterTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/entity/ApplicationRepositoryTest.java
Labels: ⚡️ feature

#126 [FEATURE] 전형 순서를 ProcessType별로 관리하도록 변경
  core-application/src/main/java/gohigher/application/port/out/persistence/ApplicationPersistenceCommandPort.java
  core-application/src/main/java/gohigher/application/service/ApplicationCommandService.java
  core-application/src/test/java/gohigher/application/service/ApplicationCommandServiceTest.java
  core-application/src/test/java/gohigher/application/service/ApplicationQueryServiceTest.java
  core-domain/src/main/java/gohigher/application/ApplicationErrorCode.java
  core-domain/src/main/java/gohigher/common/JobInfo.java
  core-domain/src/main/java/gohigher/common/Processes.java
  core-domain/src/test/java/gohigher/common/ProcessesTest.java
  core-domain/src/testFixtures/java/gohigher/application/ApplicationFixture.java
  core-domain/src/testFixtures/java/gohigher/application/ProcessFixture.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationPersistenceCommandAdapter.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationJpaEntity.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationProcessJpaEntity.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationRepository.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationPersistenceCommandAdapterTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationPersistenceQueryAdapterTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationProcessPersistenceQueryAdapterTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/entity/ApplicationRepositoryTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/fixtureConverter/ApplicationFixtureConverter.java
Labels: ⚡️ feature, 🛠️ refactor

#133 [REFACTOR] dev 환경 테이블 재배포
  out-adapter-persistence-jpa/src/main/resources/persistence/application-test.yml
Labels: 🛠️ refactor

#134 [FEATURE] 지원서 간편수정 API 생성
  core-application/src/main/java/gohigher/application/port/in/ApplicationCommandPort.java
  core-application/src/main/java/gohigher/application/port/in/SimpleApplicationUpdateRequest.java
  core-application/src/main/java/gohigher/application/port/out/persistence/ApplicationPersistenceCommandPort.java
  core-application/src/main/java/gohigher/application/service/ApplicationCommandService.java
  core-domain/src/main/java/gohigher/application/Application.java
  core-domain/src/main/java/gohigher/common/JobInfo.java
  core-domain/src/main/java/gohigher/common/Process.java
  core-domain/src/main/java/gohigher/common/Processes.java
  core-domain/src/test/java/gohigher/application/ApplicationTest.java
  core-domain/src/test/java/gohigher/common/ProcessesTest.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationCommandController.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationCommandControllerDocs.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationPersistenceCommandAdapter.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationJpaEntity.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationProcessJpaEntity.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationPersistenceCommandAdapterTest.java
Labels: ⚡️ feature

#136 [REFACTOR] auto-ddl validate
  out-adapter-persistence-jpa/src/main/resources/persistence/application-test.yml
Labels: 🛠️ refactor

#143 [REFACTOR] 같이 유지하던 지원 예정과 서류 전형의 생명주기를 분리
  core-application/src/main/java/gohigher/application/port/in/SimpleApplicationProcessRequest.java
  core-application/src/main/java/gohigher/application/port/in/SpecificApplicationProcessRequest.java
  core-application/src/main/java/gohigher/application/port/in/UnscheduledProcessRequest.java
  core-application/src/test/java/gohigher/application/service/ApplicationQueryServiceTest.java
  core-domain/src/main/java/gohigher/application/ApplicationErrorCode.java
  core-domain/src/main/java/gohigher/common/Process.java
  core-domain/src/main/java/gohigher/common/Processes.java
  core-domain/src/test/java/gohigher/common/ProcessesTest.java
Labels: 🛠️ refactor

#148 [FIX] 누락된 애너테이션 추가
  in-adapter-api/src/main/java/gohigher/application/ApplicationCommandController.java
Labels: 🚨 fix

#151 [FIX] 애너테이션 수정
  core-application/src/main/java/gohigher/application/port/in/SimpleApplicationUpdateRequest.java
Labels: 🚨 fix

#149 [FEATURE] logging 설정
  bootstrap/build.gradle
  bootstrap/src/main/java/gohigher/logging/HibernateConfig.java
  bootstrap/src/main/java/gohigher/logging/LoggingFilter.java
  bootstrap/src/main/java/gohigher/logging/MaskingPatternLayout.java
  bootstrap/src/main/java/gohigher/logging/QueryCountInspector.java
  bootstrap/src/main/resources/logback-spring.xml
  bootstrap/src/main/resources/logback/console-appender.xml
  bootstrap/src/main/resources/logback/file-error-appender.xml
  bootstrap/src/main/resources/logback/file-info-appender.xml
  bootstrap/src/main/resources/logback/file-slow-sql-appender.xml
  in-adapter-api/src/main/java/gohigher/exception/ControllerAdvice.java
Labels: ⚡️ feature

#144 [TEST] E2E 테스트 틀 작성
  bootstrap/build.gradle
  bootstrap/src/test/java/gohigher/acceptance/AcceptanceTest.java
  bootstrap/src/test/java/gohigher/acceptance/ApplicationAcceptanceTest.java
  bootstrap/src/test/java/gohigher/support/DatabaseCleanUp.java
  core-application/src/main/java/gohigher/application/port/in/SimpleApplicationRequest.java
  out-adapter-persistence-jpa/src/main/java/gohigher/user/entity/DesiredPositionJpaEntity.java
Labels: 🧪 test

#154 [DOCUMENT] gitignore에 추가
  .gitignore
Labels: 📖 documentation
