Repository team-go-higher/backend, pull requests merged in 2024-05, with the labels that each got.

#202 [FEATURE] 나의 지원서 모아보기 기능 구현
  .github/workflows/ci.yml
  bootstrap/src/test/java/gohigher/acceptance/AcceptanceTest.java
  bootstrap/src/test/java/gohigher/acceptance/ApplicationAcceptanceTest.java
  build.gradle
  core-application/src/main/java/gohigher/application/port/in/ApplicationQueryPort.java
  core-application/src/main/java/gohigher/application/port/in/MyApplicationRequest.java
  core-application/src/main/java/gohigher/application/port/in/MyApplicationResponse.java
  core-application/src/main/java/gohigher/application/port/out/persistence/ApplicationPersistenceQueryPort.java
  core-application/src/main/java/gohigher/application/service/ApplicationQueryService.java
  core-domain/src/main/java/gohigher/application/ApplicationErrorCode.java
  core-domain/src/main/java/gohigher/application/search/ApplicationSortingType.java
  core-domain/src/main/java/gohigher/common/ProcessType.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationQueryController.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationQueryControllerDocs.java
  in-adapter-api/src/main/java/gohigher/config/AuthConfig.java
  out-adapter-persistence-jpa/build.gradle
  out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationPersistenceQueryAdapter.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationJpaEntity.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationProcessJpaEntity.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationRepository.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationRepositoryCustom.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationRepositoryCustomImpl.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/dto/response/ProcessWithApplicationResponse.java
  out-adapter-persistence-jpa/src/main/java/gohigher/config/JpaQueryDslConfig.java
  out-adapter-persistence-jpa/src/test/java/gohigher/.gitkeep
  out-adapter-persistence-jpa/src/test/java/gohigher/JpaQueryTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationPersistenceCommandAdapterTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationProcessPersistenceCommandAdapterTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/ApplicationProcessPersistenceQueryAdapterTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/entity/ApplicationRepositoryCustomImplTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/entity/ApplicationRepositoryTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/config/JpaTestConfig.java
  out-adapter-persistence-jpa/src/test/java/gohigher/position/DesiredPositionPersistenceCommandAdapterTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/position/PositionPersistenceQueryAdapterTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/user/UserRepositoryTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/user/entity/RefreshTokenRepositoryTest.java
Labels: ⚡️ feature

#204 [FEATURE] 스위치(완료 여부) 변경 기능 API 구현
  bootstrap/src/test/java/gohigher/acceptance/AcceptanceTest.java
  bootstrap/src/test/java/gohigher/acceptance/ApplicationAcceptanceTest.java
  core-application/src/main/java/gohigher/application/port/in/ApplicationCommandPort.java
  core-application/src/main/java/gohigher/application/port/in/CompletedUpdatingRequest.java
  core-application/src/main/java/gohigher/application/port/in/CompletedUpdatingResponse.java
  core-application/src/main/java/gohigher/application/port/in/SpecificApplicationRequest.java
  core-application/src/main/java/gohigher/application/port/in/SpecificApplicationUpdateRequest.java
  core-application/src/main/java/gohigher/application/port/out/persistence/ApplicationPersistenceCommandPort.java
  core-application/src/main/java/gohigher/application/service/ApplicationCommandService.java
  core-application/src/test/java/gohigher/application/service/ApplicationCommandServiceTest.java
  core-domain/src/main/java/gohigher/application/Application.java
  core-domain/src/main/java/gohigher/application/ApplicationErrorCode.java
  core-domain/src/main/java/gohigher/application/CompletedSwitch.java
  core-domain/src/test/java/gohigher/application/CompletedSwitchTest.java
  core-domain/src/testFixtures/java/gohigher/application/ApplicationFixture.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationCommandController.java
  in-adapter-api/src/main/java/gohigher/application/ApplicationCommandControllerDocs.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/ApplicationPersistenceCommandAdapter.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationJpaEntity.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/entity/ApplicationRepositoryTest.java
  out-adapter-persistence-jpa/src/test/java/gohigher/fixtureConverter/ApplicationFixtureConverter.java
Labels: ⚡️ feature, 🛠️ refactor

#208 [REFACTOR] 지원서 조회하기와 관련된 API에 대한 리팩토링
  bootstrap/src/test/java/gohigher/acceptance/ApplicationAcceptanceTest.java
  core-application/src/main/java/gohigher/application/port/in/MyApplicationResponse.java
  core-domain/src/main/java/gohigher/common/ProcessType.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationRepository.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/ApplicationRepositoryCustomImpl.java
  out-adapter-persistence-jpa/src/main/java/gohigher/application/entity/dto/response/ProcessWithApplicationResponse.java
  out-adapter-persistence-jpa/src/test/java/gohigher/application/entity/ApplicationRepositoryCustomImplTest.java
Labels: 🛠️ refactor
